//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadyInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> AnnualMilage { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
